Implemented RecyclerView for MoviesList and for Actors.
Pashacabu/HW2 pull request #3
Opened 2020-12-06 10:54 UTC by Pashacabu

Implemented clickListener for both RecyclerViews ( the one for actors is under comments)
Backstack and screen rotation is working correctly
![Screenshot_1607251630](https://user-images.githubusercontent.com/70441207/101278141-7f15f900-37ca-11eb-9068-dea26e953081.png)
![Screenshot_1607251640](https://user-images.githubusercontent.com/70441207/101278143-80472600-37ca-11eb-9864-6c1e7e435889.png)
![Screenshot_1607251654](https://user-images.githubusercontent.com/70441207/101278144-80472600-37ca-11eb-86b6-477fc7532820.png)
![Screenshot_1607252037](https://user-images.githubusercontent.com/70441207/101278145-80dfbc80-37ca-11eb-85c8-49c82073ab34.png)

2020-12-06 17:36 UTC, PaulXIII requested changes

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MainActivity.kt
> +//    var fragmentMovieDetails=MovieDetails()
Комментарии лучше удалить т.к. не несет важной информации

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +        actorName.text=context.getString(actor.name)
Можно заменить на `actorName.text=actorName.context.getString(actor.name)` и тогда поле `private val context : Context = view.context` не понадобиться

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MoviesList.kt
> +          activity?.supportFragmentManager?.beginTransaction()
Можно заменить на вызов через `let{}` функцию

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +            "Avengers: End Game" -> actors = ActorData().avengers()
Лучше заменить на константы со значениями

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesData.kt
> +                Movie("Avengers: End Game", "13+", 4, "Action, Adventure, Drama", 125, 137, R.drawable.poster_avengers, R.drawable.background, R.string.avengers_storyline, ActorData().avengers()),
Строки лучше вызывать через ресурсы

2020-12-06 17:36 UTC, PaulXIII commented on app/src/main/res/layout-land/movie_details_fragment.xml
> +            android:layout_height="298dp"
Размеры лучше использовать через ресурсы

2020-12-06 18:56 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MainActivity.kt
> +//    var fragmentMovieDetails=MovieDetails()
Согласен, это остатки от процесса, комментил пока разбирался как сделать, а стереть забыл

2020-12-06 18:57 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +        actorName.text=context.getString(actor.name)
Спасибо, не догадался о такой возможности

2020-12-06 18:57 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MoviesList.kt
> +          activity?.supportFragmentManager?.beginTransaction()
Не совсем понимаю выгоду. Здесь это нужно чтобы избавиться от safe call-ов?

2020-12-06 18:59 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesData.kt
> +                Movie("Avengers: End Game", "13+", 4, "Action, Adventure, Drama", 125, 137, R.drawable.poster_avengers, R.drawable.background, R.string.avengers_storyline, ActorData().avengers()),
Не могу разобраться, как получить тут строки по их R.string.xxx Подскажи пожалуйста.

2020-12-06 19:04 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +            "Avengers: End Game" -> actors = ActorData().avengers()
Просто создать константы и приравнять их соответствующим строкам это то, что ты имеешь в виду?
Вообще хотелось бы тогда сослаться на R.string.xxx, но не могу разобраться как константе присвоить значение строки по её имени в strings.

2020-12-06 21:35 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MoviesList.kt
> +          activity?.supportFragmentManager?.beginTransaction()
Точно. safe call будет только при вызове `supportFragmentManager`

2020-12-08 17:57 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesData.kt
> +                Movie("Avengers: End Game", "13+", 4, "Action, Adventure, Drama", 125, 137, R.drawable.poster_avengers, R.drawable.background, R.string.avengers_storyline, ActorData().avengers()),
Названия фильмов перенсим в ресурсы и заменяем в классе `Movie` поле `title` на `val titleRes:Int`
Т.е. в ресурсах название фильма будет выглядеть примерно так 
`<string name="avangers_title">Avengers: End Game</string>`
В методе `onBindMovieData` задаем текст через `title.setText(movie.titleRes)`

2020-12-08 18:09 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesData.kt
> +                Movie("Avengers: End Game", "13+", 4, "Action, Adventure, Drama", 125, 137, R.drawable.poster_avengers, R.drawable.background, R.string.avengers_storyline, ActorData().avengers()),
Павел, спасибо, я если честно уже и сам до этого додумался, просто не успел ещё сделать или отписаться. Изначально я был настроен получать именно значения строк, а не ссылки на них, вот и "не мог шагнуть в сторону" Оказывается, если подумать, то все решаемо))

2020-12-17 18:03 UTC, PaulXIII requested changes

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        movieTitle = arguments?.getInt(TITLE) as Int
Можно заменить часть с `as Int` на вызов значения по умолчанию `?:0`

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +//        Toast.makeText(context, context?.getString(movieTitle), Toast.LENGTH_SHORT)
Не нужный коммент

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
>  //        Toast.makeText(context, movie.title, Toast.LENGTH_SHORT).show()
Не нужный коммент

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        pgRating.text=context?.getString(movie.pgRating)
Текст можно поставить напрямую через ресурсы т.е. `pgRating.setText(movie.pgRating)`

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        title.text= context?.getString(movie.title)
Текст можно поставить напрямую через ресурсы т.е. `title.setText(movie.title)`

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        tags.text = context?.getString(movie.tags)
Текст можно поставить напрямую через ресурсы т.е. `tags.setText(movie.tags)`

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MoviesList.kt
> +//            Toast.makeText(context, context?.resources?.getString(title)+" is selected in MoviesList", Toast.LENGTH_SHORT).show()
Не нужный коммент

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +//}
Не нужный коммент

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +        actorName.text=actorName.context.getString(actor.name)
Текст можно поставить напрямую через ресурсы т.е. `actorName.setText(actor.name)`

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesListAdapter.kt
> +            pgRating.text = context.resources.getString(movie.pgRating)
Таже ситуация с ресурсами

2020-12-17 18:03 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesListAdapter.kt
> +            tagLine.text = context.resources.getString(movie.tags)
Тоже самое

2020-12-18 18:57 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        pgRating.text=context?.getString(movie.pgRating)
Да, зачем-то я все усложнил, спасибо)

2020-12-19 11:19 UTC, PaulXIII approved these changes

2020-12-19 12:40 UTC, merged