Hw5 coroutines
Pashacabu/HW2 pull request #4
Opened 2020-12-18 20:27 UTC by Pashacabu

Implemented coroutines for loading data for movies/actors using JsonLoad.kt functions
Implemented Glide library for showing posters/backdrops/actors photos

![Screenshot_1608323004](https://user-images.githubusercontent.com/70441207/102658158-1181a980-4188-11eb-9bd9-829779a4b4dc.png)
![Screenshot_1608323010](https://user-images.githubusercontent.com/70441207/102658160-12b2d680-4188-11eb-80dd-af1fcce70b76.png)

2020-12-19 18:22 UTC, PaulXIII requested changes
По коду общее замечание: не везде одинаковый стиль. Обычно исправляется через вызов команды `Reformat code` или с клавиатуры `Ctrl + Alt + L`

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        movie = runBlocking { job2.await() }
`runBlocking` здесь явно избыточен. Можно сделать через обычный `launch` с последующим обновлением полей.

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        val job2 = coroutineScope.async {
`coroutineScope` также нужно будет отменять когда фрагмент уничтожиться

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MoviesList.kt
> +        runBlocking { adapter.loadMoviesList(deferred.await()) }
Также достточно `launch`

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/ActorData.kt
> +class ActorData {
А здесь этот класс точно нужен?

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/movieDetailsRecyclerView/MovieDetailsAdapter.kt
> +    var actors : List<com.pashcabu.hw2.data.Actor> = listOf()
Уже используется импорт `com.pashcabu.hw2.data.Actor`

2020-12-19 18:22 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/moviesListRecyclerView/MoviesData.kt
> +class MoviesData {
А здесь этот класс точно нужен?

2020-12-19 20:12 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MovieDetails.kt
> +        movie = runBlocking { job2.await() }
Павел, никак не могу разобраться, как вернуть что-то из корутины, используя launch, помоги пожалуйста - покажи где прочитать

2020-12-24 14:48 UTC, PaulXIII approved these changes
В сравнении с предыдущей версией есть большая разница в лучшую сторону.
Отлично сделано:thumbsup:

2020-12-24 16:01 UTC, Pashacabu commented
> В сравнении с предыдущей версией есть большая разница в лучшую сторону.
> Отлично сделано:thumbsup:

Спасибо, ты мне очень помог)

2020-12-26 09:50 UTC, merged