Tried to implement MVVM pattern
Pashacabu/HW2 pull request #5
Opened 2020-12-28 17:15 UTC by Pashacabu

Павел, привет, идею с MVVM я, вроде, понял. Смысл убрать от UI всю логику и данные и передавать во ViewModel запросы, подписавшись при этом на обновления данных, которые будут отображаться.
Однако с реализацией понял не до конца.(или совсем, это не мне оценивать, хех)
У меня получается данные обновляются каждый раз, как происходит поворот экрана и я не смог это побороть.

2020-12-29 14:20 UTC, PaulXIII requested changes

2020-12-29 14:20 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        viewModelScope.launch {
Можно добавить проверку для `mutableMoviesListData` при повторном вызове. Если есть значение в `mutableMoviesListData` то загружать ничего не нужно

2020-12-29 14:51 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        viewModelScope.launch {
Спасибо, это было на поверхности, но сам не додумался.(хотя теперь вспоминаю, что даже на лекции говорили, что ViewModel может сохранять в себе данные, чтобы их не запрашивать каждый раз. А я все пытался в фрагментах проверять, загружались ли уже данные.

2020-12-29 15:37 UTC, PaulXIII requested changes

2020-12-29 15:37 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
А почему проверка значения с помощью `isEmpty()` не подойдет?

2020-12-29 15:45 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
Можно и через неё, только все равно же через .value обращаться, но тогда из-за null safety нужно будет еще  дописывать в конец условия ==true. Да и однообразия ради по аналогии с проверкой данных на конкретный фильм решил сделать так.

2021-01-02 12:00 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
Не обязательно. Для коллекций есть метод `isNullOrEmpty()`. Просто в данном случае пытаемся сравнить одну пустую коллекцию с другой, а так лучше не делать.

2021-01-09 04:27 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
Павел, я исправлю, но хотелось бы знать, а что в этом плохого?

2021-01-09 11:05 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
Когда вызываем `mutableMoviesListData.value` то при наличии получим объект коллекции и при сравнении с `emptyList<Movie>()` мы сравниваем два разным объекта с различными `hashCode`.
Про сравнение объектов хорошо написано здесь https://habr.com/ru/post/168195/

2021-01-09 16:09 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +        if (mutableMoviesListData.value == emptyList<Movie>()) {
Спасибо, я прочитаю.

2021-02-01 15:11 UTC, merged