Hw7 api
Pashacabu/HW2 pull request #6
Opened 2021-01-10 19:20 UTC by Pashacabu

Basic usage of OkHttp, Retrofit and TMDB API

List of now playing movies (1 page) is loading
Movie details are loaded for every selected movie.

More functions are to be added further.
![Screenshot_1610306344](https://user-images.githubusercontent.com/70441207/104133002-e60e6b00-5391-11eb-8b7a-8383d93d7a09.png)
![Screenshot_1610306355](https://user-images.githubusercontent.com/70441207/104133003-e7d82e80-5391-11eb-8f91-d30657cb4a7e.png)

2021-01-11 16:30 UTC, PaulXIII requested changes

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/Cast.kt
> +//	val order: Int? = null
Стоит удалить весь закоментированный код

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetailsResponse.kt
> +//	val status: String? = null
Стоит удалить весь закоментированный код

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieListResponse.kt
> +//	val popularity: Double? = null,
Стоит удалить весь закоментированный код

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MovieDetailsFragment.kt
> +const val imageBaseUrl = "https://image.tmdb.org/t/p/w780"
Константы лучше хранить в `companion object`

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/NetworkModule.kt
> +const val api_key = "690d3ea0f7ef1f69512be4c95fc7a886"
Константы лучше хранить в `companion object`

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/recyclerAdapters/MovieDetailsAdapter.kt
> +const val baseImageUrl = "https://image.tmdb.org/t/p/w185"
Константы лучше хранить в `companion object`

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/recyclerAdapters/MoviesListAdapter.kt
> +const val imageBaseUrl = "https://image.tmdb.org/t/p/w185"
Константы лучше хранить в `companion object`

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +                        val listOfMovies = NetworkModule().apiService.getMoviesList(api_key, pageNumber)
`NetworkModule()` можно сделать глобальной переменной

2021-01-11 16:30 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +                    if (mutableMovieDetailsData.value==null){
А стоит проверять `mutableMovieDetailsData.value` дважды?

2021-01-19 04:59 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/Cast.kt
> +//	val order: Int? = null
Я пока его оставил на случай, если при добавлении ещё функций потребуются эти поля

2021-01-19 05:00 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MovieDetailsResponse.kt
> +//	val status: String? = null
Здесь тоже пока оставил на случай надобности

2021-01-19 05:01 UTC, Pashacabu commented on app/src/main/java/com/pashcabu/hw2/MyViewModel.kt
> +                    if (mutableMovieDetailsData.value==null){
Здесь, конечно нет, это я зря)

2021-01-26 19:48 UTC, PaulXIII requested changes

2021-01-26 19:48 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/views/adapters/NewMoviesListAdapter.kt
> +                    MyViewModel().showLoading()
А точно здесь нужно создавать новую `MyViewModel`?

2021-01-26 19:48 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/views/MoviesListFragment.kt
> +        val listener = MyScrollListener {
Похоже в `MyScrollListener` не хватает `callback`

2021-02-01 07:36 UTC, PaulXIII approved these changes

2021-02-01 15:11 UTC, merged