Hw10 deep links&notifications
Pashacabu/HW2 pull request #9
Opened 2021-03-18 16:39 UTC by Pashacabu

Notification for a new movie (from Now Playing) with the highest rating added
Notification for a most rated movie from DB's Now Playing table if there is no new movies in Now Playing
Watch later button was added to schedule movie watch in calendar
Logic for asking for calendar permission added
![Screenshot_1616084336](https://user-images.githubusercontent.com/70441207/111663224-a779ae80-8821-11eb-9b9e-ad1d2c4242ed.png)
![Screenshot_1616084537](https://user-images.githubusercontent.com/70441207/111663229-a8124500-8821-11eb-9c21-3743d147ff05.png)
![Screenshot_1616084616](https://user-images.githubusercontent.com/70441207/111663230-a8aadb80-8821-11eb-969e-7767a8735555.png)
![Screenshot_1616084621](https://user-images.githubusercontent.com/70441207/111663232-a8aadb80-8821-11eb-8449-f6c32056362e.png)
![Screenshot_1616084688](https://user-images.githubusercontent.com/70441207/111663234-a9437200-8821-11eb-884a-44aad8fd0408.png)
![Screenshot_1616084329](https://user-images.githubusercontent.com/70441207/111663236-a9437200-8821-11eb-8348-b4b0546c7fa2.png)

2021-03-19 07:42 UTC, PaulXIII requested changes

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/model/DBHandler.kt
> +//        clearGenres()
Стоит удалить не используемый код

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/model/MyWorker.kt
> +//            refreshDB()
Стоит удалить не используемый код

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/model/MyWorker.kt
> +        if (difference?.isNotEmpty() == true) {
Здесь можно использовать `isNullOrEmpty()`

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/model/MyWorker.kt
> +        }
Код для определения `mostRatedMovie`  строки `65:74` можно перенести в отдельный метод

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/view_model/MoviesListViewModel.kt
> +//        worker.enqueue(singleWorkRequest) //for testing
Стоит удалить не используемый код

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/views/MovieDetailsFragment.kt
> +        fun newInstance(/*endpoint: String,*/ movieID: Int): MovieDetailsFragment {
Параметр `endpoint` стоит удалить

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/views/MoviesListFragment.kt
> +                ?.add(R.id.fragment_container, MovieDetailsFragment.newInstance(/*"", */movieID))
Строку для параметра `endpoint` стоит удалить

2021-03-19 07:42 UTC, PaulXIII commented on app/src/main/java/com/pashcabu/hw2/views/MoviesListFragment.kt
> +    }
Метод без логики. Стоит удалить

2021-03-19 07:42 UTC, PaulXIII commented on app/build.gradle
> +        minSdkVersion 26
Нужно поднимать `minSdkVersion`?

2021-03-21 07:28 UTC, Pashacabu commented on app/build.gradle
> +        minSdkVersion 26
Пожалуй нет, просто нужно создавать NotificationChanel только при sdk > 25. Добавил такую проверку

2021-03-22 18:59 UTC, PaulXIII approved these changes

2021-03-23 16:16 UTC, merged